`timescale 1ns / 1ps
//============================================================================
// Testbench: tb_riscv_core
// Auto-generated by RTL Design Agent
// Date: 2026-04-01
//============================================================================

module tb_riscv_core;

   // ─── Clock & Reset ─────────────────────────────────────
   logic clk;
   logic rst_n;

   // Clock generation: 100MHz
   initial clk = 0;
   always #5 clk = ~clk;

   // ─── DUT Instantiation ─────────────────────────────────
   // TODO: Add port connections
   riscv_core u_dut (
      .clk   (clk),
      .rst_n (rst_n)
      // TODO: connect remaining ports
   );

   // ─── Test Stimulus ─────────────────────────────────────
   initial begin
      $display("=== Starting riscv_core Testbench ===");

      // Reset
      rst_n = 0;
      #100;
      rst_n = 1;
      #50;

      // TODO: Add test vectors here

      #1000;
      $display("=== Test Complete ===");
      $finish;
   end

   // ─── Waveform Dump ─────────────────────────────────────
   initial begin
      $dumpfile("tb_riscv_core.vcd");
      $dumpvars(0, tb_riscv_core);
   end

endmodule
