`timescale 1ns / 1ps
//============================================================================
// Testbench: tb_test_counter
// Auto-generated by RTL Design Agent
// Date: 2026-04-06
//============================================================================

module tb_test_counter;

   // ─── Clock & Reset ─────────────────────────────────────
   reg clk;
   reg rst_n;

   // Clock generation: 100MHz
   initial clk = 0;
   always #5 clk = ~clk;

   // ─── DUT Instantiation ─────────────────────────────────
   // TODO: Add port connections
   test_counter u_dut (
      .clk   (clk),
      .rst_n (rst_n)
      // TODO: connect remaining ports
   );

   // ─── Test Stimulus ─────────────────────────────────────
   initial begin
      $display("=== Starting test_counter Testbench ===");

      // Reset
      rst_n = 0;
      #100;
      rst_n = 1;
      #50;

      // TODO: Add test vectors here

      #1000;
      $display("=== Test Complete ===");
      $finish;
   end

   // ─── Waveform Dump ─────────────────────────────────────
   initial begin
      $dumpfile("tb_test_counter.vcd");
      $dumpvars(0, tb_test_counter);
   end

endmodule
