"""
Automatic file management for the RTL Design Agent.
Creates project directories, writes RTL files, and manages the workspace —
just like Cursor/Antigravity auto-creates files.
"""

from __future__ import annotations
import os
import re
import json
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass, field, asdict


@dataclass
class FileAction:
    """Represents a single file creation/modification action."""
    action: str         # "created", "modified", "deleted"
    filepath: str       # absolute path
    filename: str       # just the name
    module_name: str    # RTL module name
    lines: int          # number of lines
    timestamp: str      # ISO timestamp


@dataclass
class ProjectWorkspace:
    """Manages the auto-created project workspace."""
    root_dir: str
    project_name: str
    files: list[FileAction] = field(default_factory=list)
    structure: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "root_dir": self.root_dir,
            "project_name": self.project_name,
            "files": [asdict(f) for f in self.files],
            "structure": self.structure,
        }


def create_project_workspace(base_dir: str, project_name: str) -> ProjectWorkspace:
    """
    Create a full project directory structure for an RTL design.
    Similar to how Cursor scaffolds a project.
    
    Structure:
      <project_name>/
        ├── rtl/           # RTL source files
        ├── tb/            # Testbench files
        ├── docs/          # Documentation
        ├── sim/           # Simulation scripts
        └── README.md      # Auto-generated README
    """
    # Clean project name
    clean_name = re.sub(r'[^\w\-]', '_', project_name.lower().strip())
    project_dir = os.path.join(base_dir, clean_name)

    # Create directory structure
    dirs = {
        "root": project_dir,
        "rtl": os.path.join(project_dir, "rtl"),
        "tb": os.path.join(project_dir, "tb"),
        "docs": os.path.join(project_dir, "docs"),
        "sim": os.path.join(project_dir, "sim"),
    }

    for d in dirs.values():
        os.makedirs(d, exist_ok=True)

    workspace = ProjectWorkspace(
        root_dir=project_dir,
        project_name=clean_name,
        structure=dirs,
    )

    return workspace


def write_rtl_file(
    workspace: ProjectWorkspace,
    code: str,
    module_name: str,
    language: str = "verilog",
) -> FileAction:
    """
    Write a single RTL module to a file in the workspace.
    Auto-detects module name if not provided.
    Returns a FileAction describing what was done.
    """
    ext = ".sv" if language == "systemverilog" else ".v"
    filename = f"{module_name}{ext}"
    filepath = os.path.join(workspace.structure["rtl"], filename)

    # Write the file
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(code)

    lines = code.count("\n") + 1
    action = FileAction(
        action="created",
        filepath=filepath,
        filename=filename,
        module_name=module_name,
        lines=lines,
        timestamp=datetime.now().isoformat(),
    )
    workspace.files.append(action)
    return action


def write_composed_file(
    workspace: ProjectWorkspace,
    code: str,
    project_name: str,
    language: str = "verilog",
) -> FileAction:
    """
    Write the full composed design (all modules in one file) to the workspace.
    """
    ext = ".sv" if language == "systemverilog" else ".v"
    filename = f"{project_name}_top{ext}"
    filepath = os.path.join(workspace.structure["rtl"], filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(code)

    lines = code.count("\n") + 1
    action = FileAction(
        action="created",
        filepath=filepath,
        filename=filename,
        module_name=f"{project_name}_top",
        lines=lines,
        timestamp=datetime.now().isoformat(),
    )
    workspace.files.append(action)
    return action


def write_readme(workspace: ProjectWorkspace, spec: str, language: str) -> FileAction:
    """Auto-generate a README.md for the project."""
    lang_label = "SystemVerilog" if language == "systemverilog" else "Verilog"

    # List RTL files
    rtl_files = [f for f in workspace.files if f.filepath.endswith(('.v', '.sv'))]
    file_list = "\n".join(f"  - `{f.filename}` — {f.module_name} ({f.lines} lines)" for f in rtl_files)
    total_lines = sum(f.lines for f in rtl_files)

    readme = f"""# {workspace.project_name}

> Auto-generated by **RTL Design Agent** on {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Overview
Language: **{lang_label}**
Total RTL Lines: **{total_lines}**
Files: **{len(rtl_files)}**

## File Structure
```
{workspace.project_name}/
├── rtl/           # RTL source files
│   {chr(10).join('├── ' + f.filename for f in rtl_files)}
├── tb/            # Testbench files (todo)
├── docs/          # Documentation
├── sim/           # Simulation scripts
└── README.md
```

## RTL Files
{file_list}

## Specification
{spec}
"""

    filepath = os.path.join(workspace.root_dir, "README.md")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(readme)

    action = FileAction(
        action="created",
        filepath=filepath,
        filename="README.md",
        module_name="documentation",
        lines=readme.count("\n") + 1,
        timestamp=datetime.now().isoformat(),
    )
    workspace.files.append(action)
    return action


def write_testbench_stub(
    workspace: ProjectWorkspace,
    module_name: str,
    ports_info: str,
    language: str = "verilog",
) -> FileAction:
    """Write a basic testbench stub file."""
    ext = ".sv" if language == "systemverilog" else ".v"
    filename = f"tb_{module_name}{ext}"
    filepath = os.path.join(workspace.structure["tb"], filename)

    if language == "systemverilog":
        tb_code = f"""`timescale 1ns / 1ps
//============================================================================
// Testbench: tb_{module_name}
// Auto-generated by RTL Design Agent
// Date: {datetime.now().strftime('%Y-%m-%d')}
//============================================================================

module tb_{module_name};

   // ─── Clock & Reset ─────────────────────────────────────
   logic clk;
   logic rst_n;

   // Clock generation: 100MHz
   initial clk = 0;
   always #5 clk = ~clk;

   // ─── DUT Instantiation ─────────────────────────────────
   // TODO: Add port connections
   {module_name} u_dut (
      .clk   (clk),
      .rst_n (rst_n)
      // TODO: connect remaining ports
   );

   // ─── Test Stimulus ─────────────────────────────────────
   initial begin
      $display("=== Starting {module_name} Testbench ===");

      // Reset
      rst_n = 0;
      #100;
      rst_n = 1;
      #50;

      // TODO: Add test vectors here

      #1000;
      $display("=== Test Complete ===");
      $finish;
   end

   // ─── Waveform Dump ─────────────────────────────────────
   initial begin
      $dumpfile("tb_{module_name}.vcd");
      $dumpvars(0, tb_{module_name});
   end

endmodule
"""
    else:
        tb_code = f"""`timescale 1ns / 1ps
//============================================================================
// Testbench: tb_{module_name}
// Auto-generated by RTL Design Agent
// Date: {datetime.now().strftime('%Y-%m-%d')}
//============================================================================

module tb_{module_name};

   // ─── Clock & Reset ─────────────────────────────────────
   reg clk;
   reg rst_n;

   // Clock generation: 100MHz
   initial clk = 0;
   always #5 clk = ~clk;

   // ─── DUT Instantiation ─────────────────────────────────
   // TODO: Add port connections
   {module_name} u_dut (
      .clk   (clk),
      .rst_n (rst_n)
      // TODO: connect remaining ports
   );

   // ─── Test Stimulus ─────────────────────────────────────
   initial begin
      $display("=== Starting {module_name} Testbench ===");

      // Reset
      rst_n = 0;
      #100;
      rst_n = 1;
      #50;

      // TODO: Add test vectors here

      #1000;
      $display("=== Test Complete ===");
      $finish;
   end

   // ─── Waveform Dump ─────────────────────────────────────
   initial begin
      $dumpfile("tb_{module_name}.vcd");
      $dumpvars(0, tb_{module_name});
   end

endmodule
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(tb_code)

    lines = tb_code.count("\n") + 1
    action = FileAction(
        action="created",
        filepath=filepath,
        filename=filename,
        module_name=f"tb_{module_name}",
        lines=lines,
        timestamp=datetime.now().isoformat(),
    )
    workspace.files.append(action)
    return action


def extract_all_modules(code: str) -> list[tuple[str, str]]:
    """
    Extract individual modules from a combined RTL file.
    Returns list of (module_name, module_code) tuples.
    """
    # First strip markdown code blocks
    code_match = re.search(r"```(?:verilog|systemverilog|sv)?\s*\n(.*?)```", code, re.DOTALL)
    if code_match:
        code = code_match.group(1)

    modules = []
    # Find each module...endmodule block including any preceding comments
    pattern = r"((?://[^\n]*\n)*\s*module\s+(\w+)[\s\S]*?endmodule)"
    for match in re.finditer(pattern, code):
        full_code = match.group(1).strip()
        name = match.group(2)
        modules.append((name, full_code))

    return modules


def auto_write_all_files(
    workspace: ProjectWorkspace,
    rtl_code: str,
    spec: str,
    language: str,
) -> list[FileAction]:
    """
    Master function: automatically extract all modules from the generated code
    and write each one to its own file + testbench stubs + README.
    This is the "Cursor-like" auto-file-creation experience.
    """
    all_actions = []

    # 1) Extract individual modules
    modules = extract_all_modules(rtl_code)

    if modules:
        # Write each module to its own file
        for mod_name, mod_code in modules:
            action = write_rtl_file(workspace, mod_code, mod_name, language)
            all_actions.append(action)

        # Write the full combined file too
        code_match = re.search(r"```(?:verilog|systemverilog|sv)?\s*\n(.*?)```", rtl_code, re.DOTALL)
        full_code = code_match.group(1).strip() if code_match else rtl_code.strip()
        combined_action = write_composed_file(workspace, full_code, workspace.project_name, language)
        all_actions.append(combined_action)

        # Write testbench stubs for each module
        for mod_name, _ in modules:
            tb_action = write_testbench_stub(workspace, mod_name, "", language)
            all_actions.append(tb_action)
    else:
        # Single block of code, no module detected — write as-is
        code_match = re.search(r"```(?:verilog|systemverilog|sv)?\s*\n(.*?)```", rtl_code, re.DOTALL)
        clean_code = code_match.group(1).strip() if code_match else rtl_code.strip()
        action = write_rtl_file(workspace, clean_code, workspace.project_name, language)
        all_actions.append(action)

    # 2) Write README
    readme_action = write_readme(workspace, spec, language)
    all_actions.append(readme_action)

    # 3) Write project manifest
    manifest = {
        "project": workspace.project_name,
        "language": language,
        "generated_at": datetime.now().isoformat(),
        "files": [asdict(a) for a in all_actions],
        "total_lines": sum(a.lines for a in all_actions),
    }
    manifest_path = os.path.join(workspace.root_dir, "project.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    return all_actions


def format_file_tree(workspace: ProjectWorkspace) -> str:
    """
    Generate a pretty file tree string showing all created files,
    similar to what Cursor shows in its file panel.
    """
    lines = [f"📁 **{workspace.project_name}/**"]

    # Group files by directory
    by_dir: dict[str, list[FileAction]] = {}
    for fa in workspace.files:
        parent = os.path.dirname(fa.filepath)
        rel = os.path.relpath(parent, workspace.root_dir)
        if rel == ".":
            rel = ""
        if rel not in by_dir:
            by_dir[rel] = []
        by_dir[rel].append(fa)

    # Sort directories
    for dir_name in sorted(by_dir.keys()):
        files = by_dir[dir_name]
        if dir_name:
            icon = "📂"
            if "rtl" in dir_name:
                icon = "🔧"
            elif "tb" in dir_name:
                icon = "🧪"
            elif "docs" in dir_name:
                icon = "📄"
            lines.append(f"├── {icon} **{dir_name}/**")
            prefix = "│   "
        else:
            prefix = "├── "

        for i, fa in enumerate(files):
            is_last = (i == len(files) - 1)
            connector = "└──" if is_last else "├──"

            # File icon based on extension
            if fa.filename.endswith(('.v', '.sv')):
                if fa.filename.startswith('tb_'):
                    ficon = "🧪"
                else:
                    ficon = "📝"
            elif fa.filename.endswith('.md'):
                ficon = "📄"
            else:
                ficon = "📎"

            status_icon = "✅" if fa.action == "created" else "📝"
            lines.append(
                f"{prefix}{connector} {ficon} `{fa.filename}` "
                f"({fa.lines} lines) {status_icon}"
            )

    return "\n".join(lines)
