"""
LangGraph shared state definition for the RTL Design Agent pipeline.

Supports both simple (single-module) and complex (hierarchical multi-module) designs.
The AgentState flows through: Planner → [Decomposer] → Coder(s) → Composer → Reviewer
"""

from __future__ import annotations
from typing import TypedDict, Literal, Annotated
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class SubmoduleSpec(TypedDict):
    """Specification for a single submodule in a hierarchical design."""
    name: str           # Module name
    spec: str           # Detailed spec for this module
    code: str           # Generated code (filled by coder)
    status: str         # "pending", "generated", "reviewed"


class AgentState(TypedDict):
    """Shared state passed between all agent nodes in the graph."""

    # Chat message history (accumulated by LangGraph's add_messages reducer)
    messages: Annotated[list[BaseMessage], add_messages]

    # The user's original design request
    user_prompt: str

    # Structured specification generated by the Planner agent
    spec: str

    # ─── Hierarchical decomposition fields ────────────────────────
    # Whether the design requires hierarchical decomposition
    is_hierarchical: bool

    # List of submodule specs (for hierarchical designs)
    submodule_specs: list[SubmoduleSpec]

    # Index of the submodule currently being coded
    current_submodule_idx: int

    # Accumulated code from all submodules (built up by composer)
    accumulated_code: str

    # ─── Single-module fields ─────────────────────────────────────
    # Generated RTL code from the Coder agent (single module or final composed)
    rtl_code: str

    # Review feedback from the Reviewer agent
    review: str

    # How many revision cycles have occurred (max 3)
    revision_count: int

    # Current pipeline status
    status: Literal["planning", "decomposing", "coding", "composing", "reviewing", "complete", "error"]

    # Target HDL language
    language: Literal["verilog", "systemverilog"]

    # Final decision from reviewer
    review_decision: Literal["pass", "revise", ""]
